// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIgebh7gC78P2NRoDA-bxTSsL1o0bREbE',
    appId: '1:417074762744:web:350caad432eb0c108d7c0d',
    messagingSenderId: '417074762744',
    projectId: 'streamy-c5eb9',
    authDomain: 'streamy-c5eb9.firebaseapp.com',
    storageBucket: 'streamy-c5eb9.appspot.com',
    measurementId: 'G-N11ZQDD3J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkZgdLpiPVXpIZ6FKm6OSkfsmMSk2j8lE',
    appId: '1:417074762744:android:63358d54c454b84f8d7c0d',
    messagingSenderId: '417074762744',
    projectId: 'streamy-c5eb9',
    storageBucket: 'streamy-c5eb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5kvTFygEmSI5ZjnIIvJH6GRCbHzgPoII',
    appId: '1:417074762744:ios:7c5c4cc34efd2ee68d7c0d',
    messagingSenderId: '417074762744',
    projectId: 'streamy-c5eb9',
    storageBucket: 'streamy-c5eb9.appspot.com',
    iosBundleId: 'com.example.streamy',
  );
}
